use project;
--1.Retrive all the data from the table
select * from supermarket_sales_data29;
--This will return all records from the dataset.

--2.Get the unique cities where the supermarket operates.
select DISTINCT City FROM supermarket_sales_data29;
--This will return all the unique city names from the dataset.


--3.Count the total number of sales transactions.
select count(*) AS Total_transaction from supermarket_sales_data29;
--This will return the total number of transactions recorded in the dataset.

--4.Find the different types of customer categories
select DISTINCT "Customer_type" from supermarket_sales_data29;
--This will return the unique customer type inthe dataset

--5. Retrive all sales transections made by female
select * from supermarket_sales_data29 where Gender='Female';
--This will return all recods where the customer is female 

--6.Get the total number of male and female customer 
Select Gender,count(*) As Total_Customers from supermarket_sales_data29
Group By Gender;
--This will  display the count of male and female customers

--7.Find the different payment methods used in the supermarket
select distinct payment from supermarket_sales_data29;
--This will return the unique payments methods()

--8.Retrieve all records where the quantity purchased is greater than 5
Select * from supermarket_sales_data29 where Quantity>5;
--This will return all transections where customers bought more than 5 items

--9.get the transaction details for a specific invoice ID
select * from supermarket_sales_data29 where "Invoice_ID"='750-67-8428';
--This will return the details of the specified transaction.

--10.Get the total revenue  generated from all sales.
select sum(Total) AS Total_Revenue from supermarket_sales_data29;
--This will return the total revenue generated by the supermarket 

--11 Retrive the total sales per branch
select Branch, Sum(Total)AS Total_Sales
From supermarket_sales_data29
Group BY Branch
Order By Total_Sales DESC;
--this query will return the total sales for each branch

--12. Find the top 5 most sold product line based on quantity
SELECT TOP 5 
    Product_line, 
    SUM(Quantity) AS Total_Quantity
FROM supermarket_sales_data29
GROUP BY Product_line
ORDER BY Total_Quantity DESC;
--It will return the 5 product lines with the highest quantity sold


--13.Get the average rating given by custoomer er payment method
select Payment, Avg(Rating) As Avg_Rating
From supermarket_sales_data29
Group by Payment
Order by Avg_Rating DESC;
This will display the average customer rating for each payment method

--14.find the most popular payment method
SELECT TOP 5 "Product_line" , SUM(Quantity) AS Total_Quantity
FROM supermarket_sales_data29
GROUP BY "Product_line"
ORDER BY Total_Quantity DESC;
--It will return the payment method used most frequently.

--15.Find the total revenue generated in each city.
SELECT City, SUM(Total) AS Total_Revenue
FROM supermarket_sales_data29
GROUP BY City
ORDER BY Total_Revenue DESC;
--This will display the total revenue for each city.

--16.Retrieve the gender distribution of customers.
SELECT Gender, COUNT(*) AS Total_Customers
FROM supermarket_sales_data29
GROUP BY Gender;
--This will return the number of male and female customers.


--17.Find the best-selling product line in terms of revenue.
SELECT TOP 1 Product_line, SUM(Total) AS Revenue
FROM supermarket_sales_data29
GROUP BY Product_line
ORDER BY Revenue DESC;
--This will show the product line that generated the highest revenue.


--18.Get the branch with the highest average gross income per transaction.
SELECT TOP 1 Branch, AVG(gross_income) AS Avg_Gross_Income
FROM supermarket_sales_data29
GROUP BY Branch
ORDER BY Avg_Gross_Income DESC;
--This will return the branch with the highest average gross income per transaction.

--19. Find the day of the week with the highest sale:
SELECT TOP 1
    DATENAME(WEEKDAY, Date) AS Day_Of_Week, 
    SUM(Total) AS Total_Sales
FROM supermarket_sales_data29
GROUP BY DATENAME(WEEKDAY, Date)
ORDER BY Total_Sales DESC;
--This will return the weekday with the highest total sales.


--20  Find the branch with the highest number of transactions in the evening (after 18:00).
SELECT TOP 1
    Branch, 
    COUNT(*) AS Evening_Transactions
FROM supermarket_sales_data29
WHERE CAST(FORMAT(Time, 'HH') AS INT) >= 18
GROUP BY Branch
ORDER BY Evening_Transactions DESC;
--This will show the branch that had the most transactions during the evening hours.  correct the qury as per sql server